project: recommend-lunch-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /task
  script: main.app
  login: admin
  secure: always

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"